name: Native Build

on:
  push:
    branches:
      - main
    paths:
      - mobile/app.json
      - mobile/eas.json
      - mobile/patches/**

jobs:
  build_ios:
    name: Build iOS App
    type: build
    params:
      platform: ios
      profile: preview
